# Skip all this for non-interactive shells
[[ -z "$PS1" ]] && return

# Editor
export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Path
export PATH=$PATH:$HOME/bin

# Options
export REPORTTIME=30
setopt rm_star_wait auto_continue noclobber no_bg_nice autocd correct no_flow_control no_beep appendhistory nomatch notify
# TODO: Consider
bindkey -e

# Bind keys
bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line
bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word
bindkey "^[[3~" delete-char

# Autocompletion
zstyle :compinstall filename '/home/harry/.zshrc'
autoload -Uz compinit
compinit

# Aliases
alias ls='ls --color'
alias gst='git status'
alias gc='git commit'
alias ga='git add'
alias gp='git push'
alias gl='git log'
alias gd='git diff'
alias hp='git push heroku master'
alias bi='bundle install'
alias bu='bundle update'
alias be='bundle exec'
alias gi='gem install'
alias sus='sudo pm-suspend; echo "Probably a good idea to run fon now"'
alias fon='sudo rc.d start thinkfan'
alias foff='sudo rc.d stop thinkfan'
alias f6='sudo rc.d stop thinkfan; fan6'
alias nh='sudo netcfg -r home'
alias pacman='pacman-color'
alias pacsyu='sudo pacman -Syu'
alias pacs='sudo pacman -S'
alias pacr='sudo pacman -R'

# Prompt
export PROMPT="%~ %% "
