#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Always show coloured output out of ls
alias ls='ls --color'

# Show the current git branch in the PS!
PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '

# Add RVM and the bin directoryto path
PATH=$PATH:$HOME/.rvm/bin:$HOME/bin:/opt/SenchaSDKTools-2.0.0-beta3:/opt/SenchaArchitect

# Set default editor and alias vi to it
EDITOR=vim
alias vi=$EDITOR

# Sencha (mobile dev)
export SENCHA_SDK_TOOLS_2_0_0_BETA3="/opt/SenchaSDKTools-2.0.0-beta3"

# Variables for current working (as in project, not pwd) directory
#CWNAME=yrs2012_backend
#CWDIR=$HOME/code/$CWNAME
CWDIR=$HOME/code

if [ "$TERM" = "rxvt-unicode-256color" ]; then
  TERM="rxvt-256color"
fi

# ack | less, but coloured
alias ackl='ACK_PAGER_COLOR="less -x4SRFX" ack'

# git aliases
alias gst='git status'
alias gc='git commit'
alias ga='git add'
alias gp='git push'
alias hp='git push heroku master'
alias gd='git diff'

# Go to current working directory (see $CWNAME and $CWDIR above)
alias cw='cd $CWDIR'

# bundle aliases
alias bi='bundle install'
alias bu='bundle update'
alias be='bundle exec'

# run rackup with the first non-127.0.0.1 IP
alias s="rerun -- rackup config.ru -o `ifconfig | grep "inet " | awk ' { if ($2 != \"127.0.0.1\") print $2 } ' | head -n 1`"

# fixes problems with muscle memory and singular commands
alias beets=beet

# rjb
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/jre/lib/amd64:$JAVA_HOME/jre/lib/amd64/client

